<?php
/**
 * @category	Trio
 * @package	Wizard
 */
//Trio_Wizard_Block_View
?>
<?php $w_number=0; ?>
<?php if ($this->hasValidGroup()):
    $group_collection = $this->_getCollection();
    $group=null;
    $image_path=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wizard/';
    if (count($group_collection) > 0)
    {
        $group=$group_collection->getFirstItem();
        $wizards = $this->getWizards( $group['group_id']);
    }    
    echo '<div class="wizards" id="wizards_id" style=""> 
        <form name="wizard_form" action="'.$this->getUrl().'catalogsearch/advanced/result/'.'" method="get" id="wizard_form_validate">';
         
        //echo"<pr>"; echo ' '.count($wizards).'<br/>';      
        foreach($wizards as $wizard):
            $data=$wizard->getData();
            $scope=json_decode($data["scope"],true);
            $backgr_img=($data['image'])?'background: url('.$image_path.$data['image'].') 100% 100% no-repeat;':'';
      
            $display_none=($w_number>0)?' none':'';
			if($data["view"]=='grid'):
				echo '<div class="wizard wizard-grid'.$display_none.'" id="wizard_'.$w_number.'" style="'.$backgr_img.'">';
					
					echo '<h2>'.$data["title"].'</h2>';
					$s_number=0;
					echo '<ul>';
						foreach($scope as $item):
							//print_r($item);//Array ( [option] => 5 [sort] => 1954 [delete] => [image] => IMG_20120915_150405.jpg )                           
							if($item['delete']==1){continue;}
							
							echo '<li>
									<label for="radio-'.$item['option'].'">
										<input type="radio" name="'.$data['code'].'" value="'.$item['option'].'" id="radio-'.$item['option'].'">
										<span>'.$item['option'].'</span>
										<img src="'.$image_path.$item['image'].'" alt="'.$item['option'].'" title="'.$item['option'].'">
									</label>
								 </li>';
							$s_number++;
						endforeach;
					echo '</ul>';
					//echo '<a href="#color" class="skip" >No, I don’t know. Skip this step.</a>';
					echo '<div class="buttons">
								<button class="button" type="button" onclick="wizardSkip(\''.$w_number.'\')">No, I can’t. Skip this step</button>'; 
						if($w_number>0)
						 echo '<button class="button" type="button" onclick="wizardPrevios(\''.$w_number.'\')">Previos step</button>';                   
						 echo '<button class="button" type="button" onclick="wizardNext(\''.$w_number.'\')">Next step</button>
						</div>';
				echo '</div>';
			endif;// end grid
			
			
			if($data["view"]=='list'):
				echo '<div class="wizard wizard-list'.$display_none.'" id="wizard_'.$w_number.'" style="'.$backgr_img.'">';
					
					echo '<h2>'.$data["title"].'</h2>';
					$s_number=0;
					echo '<ul>';
						foreach($scope as $item):
							//print_r($item);//Array ( [option] => 5 [sort] => 1954 [delete] => [image] => IMG_20120915_150405.jpg )                           
							if($item['delete']==1){continue;}
							
							echo '<li>
									<label for="radio-'.$item['option'].'">
										<input type="radio" name="'.$data['code'].'" value="'.$item['option'].'" id="radio-'.$item['option'].'">
										<img src="'.$image_path.$item['image'].'" alt="'.$item['option'].'" title="'.$item['option'].'">
										<div class="frame">
											<span>'.$item['option'].'</span>
										</div>
									</label>
								 </li>';
							$s_number++;
						endforeach;
					echo '</ul>';
					//echo '<a href="#color" class="skip" >No, I don’t know. Skip this step.</a>';
					echo '<div class="buttons">
								<button class="button" type="button" onclick="wizardSkip(\''.$w_number.'\')">No, I can’t. Skip this step</button>'; 
						if($w_number>0)
						 echo '<button class="button" type="button" onclick="wizardPrevios(\''.$w_number.'\')">Previos step</button>';                   
						 echo '<button class="button" type="button" onclick="wizardNext(\''.$w_number.'\')">Next step</button>
						</div>';
				echo '</div>';
			endif;// end list
            $w_number+=1;
        endforeach;//foreach $wizards
    echo '</form>';
    echo '</div>';
endif;
?>
<script type="text/javascript">
    //<![CDATA[
    jQuery.noConflict();
    var wizardsCount=<?php echo $w_number ?> ;
    var searchUrl="<?php echo $this->getUrl('/catalogsearch/advanced/result/');?>" ;
    //?name=t-name&description=t-descr&sku=t-SKU&price%5Bfrom%5D=67&price%5Bto%5D=80&color%5B%5D=26&color%5B%5D=23&gender%5B%5D=65&gender%5B%5D=36&computer_manufacturers%5B%5D=77&computer_manufacturers%5B%5D=73
    function wizardSkip(number)
    {   if( number<(wizardsCount-1) )
        {
            jQuery("#wizard_"+number ).addClass("none");
            number++;
            jQuery("#wizard_"+number ).removeClass("none");
        }
        else
        {
            document.wizard_form.submit();
        }
    }
    function wizardPrevios(number)
    {  
        jQuery("#wizard_"+number ).addClass("none");
        number--;
        jQuery("#wizard_"+number ).removeClass("none");
      
    }
    function wizardNext(number)
    {  
        if( number<(wizardsCount-1) )
        {
            jQuery("#wizard_"+number ).addClass("none");
            number++;
            jQuery("#wizard_"+number ).removeClass("none");
        } 
        else
        {
            document.wizard_form.submit();
        }
    }
    jQuery(document).ready(function(){
        
    });
    //]]>
</script>
