<? if (Mage::getStoreConfig('blog/blog/userte')): ?>
    <script src="<?php echo $this->getSkinUrl('') ?>trio_blog/js/tiny_mce/tiny_mce.js"></script>
    <script src="<?php echo $this->getSkinUrl('') ?>trio_blog/js/init_rte.js"></script>

    <script>
        // Init rte
        Trio_BlogIntId = setInterval(
        function(){
            if(typeof tinyMCE != 'undefined' && $('anchor-content')){
                initRTE();
                clearInterval(Trio_BlogIntId);
            }
        }
        ,500)
    </script>
<? endif; ?>
